# Jekyll configuration for GitHub Pages
title: Frontend Playground
description: A collection of frontend demos and examples
baseurl: "/frontend-playground"
url: "https://landsman.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - README.md

# Collections
collections_dir: .

# GitHub Pages settings
github:
  repository_url: https://github.com/landsman/frontend-playground
